In [4]:
import cv2 as cv
import numpy as np

In [5]:
img = cv.imread('KakaoTalk_20190623_191341581.png')

In [6]:
print(img[0,0])

[ 99 124  98]


In [7]:
print(img[0,0])

[ 99 124  98]


In [8]:
last_img = cv.cvtColor(img, cv.COLOR_BGR2HSV)

In [9]:
print(last_img[0,0])

[ 61  53 124]


In [10]:
img_resize=cv.resize(img,dsize=(100,100),interpolation=cv.INTER_AREA)
#dsize(x픽셀,y픽셀)

In [11]:
print(img_resize[0,0])

[ 92 116  84]


In [12]:
last_img_resize = cv.cvtColor(img_resize, cv.COLOR_BGR2HSV)

In [13]:
print(last_img_resize[0,0])

[ 68  70 116]


In [14]:
cv.imshow('image',img_resize)
cv.waitKey(0)
cv.destroyAllWindows()

In [15]:
cv.imshow('image',img)
cv.waitKey(0)
cv.destroyAllWindows()